.TH SECRET (1)
.SH NAME
secret \- send or receive data through an encrypted channel via ICMP
.SH SYNOPSIS
.B secret
[\fB\-r \fIFILE TO BE SENT\fR]
[\fB\-s \fISERVER IP ADDRESS\fR | \fISERVER HOSTNAME\fR]

.B secret
[\fB\-l]

.SH DESCRIPTION
.B secret
either sends a file over an encrypted channel (client mode) or accepts encrypted communication and saves it inside a
file (server mode). The server is able to accept data from multiple clients at once, packet loss is possible, due to no
transmission assurance being implemented.

.SH OPTIONS
.TP
.B \-l
Starts the program in server mode

.TP
.B \-r \fIFILEPATH\fR
Tells the client what file to send over the encrypted channel.

.TP
.B \-s \fISERVER IP ADDRESS\fR | \fISERVER HOSTNAME\fR
Tells the client what address to send to or what hostname to resolve into an address to send to.

.SH AUTHOR
Tadeas Topinka (xtopint00) at VUT FIT 2025